# Generated by Django 6.0.2 on 2026-03-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auction_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Living', 'Home & Living'), ('Books', 'Books'), ('Sports', 'Sports'), ('Toys', 'Toys'), ('Beauty', 'Beauty'), ('Automotive', 'Automotive'), ('Other', 'Other')], default='Other', max_length=64),
        ),
    ]
