# Generated by Django 6.0.2 on 2026-03-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Living', 'Home & Living'), ('Books', 'Books'), ('Sports', 'Sports'), ('Toys', 'Toys'), ('Beauty', 'Beauty'), ('Automotive', 'Automotive'), ('Other', 'Other')], default='Other', max_length=64, unique=True),
        ),
    ]
